Exercises XP

Last Updated: June 18th, 2025

👩‍🏫 👩🏿‍🏫 What You’ll Learn

Identify structured and unstructured data.
Convert unstructured data into structured formats.
Categorize and utilize different data types in a business context.
Learn how to import datasets directly from Kaggle.
Understand the process of importing and displaying data from a CSV file using Pandas.
Gain skills in fetching and reading JSON data from a URL using Pandas.


🛠️ What You Will Create

Classify various data sources.
Convert raw data into structured formats.
How to import the Titanic dataset from Kaggle and display its initial rows.
A script for importing the Iris dataset from a CSV file and displaying its first few rows.
How to import JSON data from a URL and display the initial entries.


🌟 Exercise 1: Identifying Data Types

Below are various data sources. Identify whether each one is an example of structured or unstructured data.

A company’s financial reports stored in an Excel file.
Photographs uploaded to a social media platform.
A collection of news articles on a website.
Inventory data in a relational database.
Recorded interviews from a market research study.

In [ ]:
# A company’s financial reports stored in an Excel file. - Structured
# Photographs uploaded to a social media platform. - Unstructured
# A collection of news articles on a website. - Unstructured
# Inventory data in a relational database. - Structured
# Recorded interviews from a market research study. - Unstructured

🌟 Exercise 2: Transformation Exercise

For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

A series of blog posts about travel experiences.
Audio recordings of customer service calls.
Handwritten notes from a brainstorming session.
A video tutorial on cooking.

In [ ]:
# A series of blog posts about travel experiences. columns of name and other releveant data.  Keep the posts in their own column, and give a new column called 'sentiment' which is figured out by some sentiment library.  This will let me know more about the unstructured text info as to the experience of the customer.  
# Audio recordings of customer service calls. columns of name and other relevant data.  transcribe recording and add column 'transcription'.  Using the transcribed text categorize the type of call. Also, do sentiment like above
# Handwritten notes from a brainstorming session. columns 'name' - name of brainstormer, 'idea' - brainstormed idea, column called 'idea_application' - what is the application of the brainstorm.
# A video tutorial on cooking. transcribe the video like we did with the audio.  Columns for ['dish','ingredients','prep_time','cook_time','category_of_dish'] category_of dish would be like Mexican or Diner food, or Cafe

🌟 Exercise 3 : Import A File From Kaggle

Note: This dataset was originally sourced from Kaggle, but for easier access, it has been made available on GitHub.

👉 Please download the dataset directly from the GitHub repository to use it in this project.

Import the train dataset. Use the train.csv file.
Print the first few rows of the DataFrame.

In [16]:
import pandas as pd

In [20]:
train = pd.read_csv('train.csv')
train.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

🌟 Exercise 4: Importing A CSV File

Use the Iris Dataset CSV.

Download the Iris dataset CSV file and place it in the same directory as your Jupyter Notebook.
Import the CSV file using Pandas.
Display the first five rows of the dataset.

In [24]:
iris = pd.read_csv('Iris_dataset.csv')
iris.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

🌟 Exercise 5 : Export A Dataframe To Excel Format And JSON Format.

Create a simple dataframe.
Export the dataframe to an excel file.
Export the dataframe to a JSON file.

In [30]:
iris.to_excel('excel_from_df.xlsx')
iris.to_json('json_from_df.json')

🌟 Exercise 6: Reading JSON Data

Use a sample JSON dataset

Import the JSON data from the provided URL.
Use Pandas to read the JSON data.
Display the first five entries of the data.

In [28]:
json_df = pd.read_json('posts.json')
json_df.head(5)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...